--- #YAML:1.0
name: Data-Page-Pageset
version: 1.02
author:
  - Chunzi <me@chunzi.org>
abstract: change long page list to be shorter and well navigate
license: perl
generated_by: Module::Build version 0.26, without YAML.pm
